### ISSUE TITLE
Weight for pre-training

### ISSUE THREAD

**Issue by LIMANONDBannapol** [zhjohnchan/ARL#2]
Thank you for your work. Is it possible to upload the weight after training with medical image captions? Or does it have some privacy issue with the medical dataset?

**Comment by zhjohnchan** [comment]
Hi,

Thanks for your attention! The reason is that the pre-processed datasets might differ due to the different environments (e.g., the version of scispacy). This will lead to different entity vocabulary, and loading weights pre-trained by me might cause the error. Thus, I did not provide that. I think one can easily replicate the results following the readme.

Thanks!

Best,
Zhihong

**Comment by LIMANONDBannapol** [comment]
Thank you for your reply. I understand! I will close the issue now.
